#!/bin/bash
# generate a custom root CA (Certificate Authority)

openssl genrsa -des3 -out MyRootCA.key 2048

openssl req \
  -x509 \
  -new \
  -nodes \
  -key MyRootCA.key \
  -sha256 \
  -days 1024 \
  -out MyRootCA.pem \
  -subj "/C=DE/ST=Sachsen/L=Dresden/O=TU Dresden/OU=Faculty of Computer Science/CN=aamcs/emailAddress=info@aamcs.com"

